# Generated by Django 4.0.1 on 2023-05-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=100, unique=True)),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_from', models.CharField(max_length=100)),
                ('flight_to', models.CharField(max_length=100)),
                ('takeoff_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('takeoff_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('flight_duration', models.FloatField()),
                ('number_of_seats', models.IntegerField()),
                ('price', models.IntegerField()),
                ('seats_booked', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('contactno', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=32)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flight_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.user')),
            ],
        ),
    ]
