# Generated by Django 4.0.1 on 2023-06-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='price',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='seats_booked',
        ),
    ]
