# Generated by Django 4.0.1 on 2023-06-13 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_flight_price_remove_flight_seats_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_duration',
        ),
    ]
