# Generated by Django 4.0.1 on 2023-06-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='number_of_seats',
            field=models.IntegerField(default=0),
        ),
    ]
