# Generated by Django 4.0.1 on 2023-06-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_flight_number_of_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='number_of_seats',
            new_name='available_seats',
        ),
        migrations.AddField(
            model_name='flight',
            name='price_business',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flight',
            name='price_economy',
            field=models.FloatField(default=0.0),
        ),
    ]
