# Generated by Django 4.0.1 on 2023-06-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_rename_number_of_seats_flight_available_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_class',
            field=models.CharField(default='business', max_length=20),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_status',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
