# Generated by Django 4.0.1 on 2023-06-14 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_seat_passenger_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(default='', max_length=10)),
                ('seat_status', models.CharField(default='', max_length=15)),
                ('seat_class', models.CharField(default='business', max_length=20)),
                ('seat_price', models.FloatField(default=0.0)),
                ('passenger_name', models.CharField(default='', max_length=50)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
