# Generated by Django 4.0.1 on 2023-06-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_booking_delete_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='available_seats',
            field=models.IntegerField(default=60),
        ),
    ]
