# Generated by Django 4.0.1 on 2023-06-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_flight_status_alter_flight_available_seats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight_Book',
        ),
    ]
